(function () {
  'use strict'
  const API = 'http://127.0.0.1:3080'
  const state = { sessions: [], current: null, history: [], models: null, modelConfig: null, connected: false, busy: false, filter: '' }
  const $ = id => document.getElementById(id)
  const text = value => typeof value === 'string' ? value : JSON.stringify(value, null, 2)
  const messageText = data => {
    const source = data && data.message ? data.message : data
    if (!source || !Array.isArray(source.content)) return ''
    return source.content.filter(part => part && part.type === 'text').map(part => part.text || '').join('')
  }
  function setConnection(ok) { state.connected = ok; $('connectionDot').className = 'dot ' + (ok ? 'online' : 'offline'); $('connectionText').textContent = ok ? '已连接' : '离线' }
  function toast(value) { const el = $('toast'); el.textContent = value; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400) }
  function parseIpc(value) {
    let current = value
    for (let i = 0; i < 3 && typeof current === 'string'; i += 1) {
      try { current = JSON.parse(current) } catch (_) { break }
    }
    return current
  }
  async function nativeInvoke(channel, payload) {
    if (!window.jade || typeof window.jade.invoke !== 'function') throw new Error('JadeView 原生桥接不可用')
    try {
      return parseIpc(await window.jade.invoke(channel, JSON.stringify(payload || {}), { timeout: 30000 }))
    } catch (_) {
      return parseIpc(await window.jade.invoke(channel, payload || {}, { timeout: 30000 }))
    }
  }
  async function rpc(method, payload) {
    const envelope = await nativeInvoke('api_request', { method, payload })
    if (!envelope.result || !envelope.result.ok) throw new Error(envelope.result?.error?.message || '请求失败')
    setConnection(true); return envelope.result.value
  }
  function titleFor(item) { return item.projections?.values?.title || (item.blank ? '新会话' : '未命名会话') }
  function timeFor(ms) { const date = new Date(ms); const today = new Date(); if (date.toDateString() === today.toDateString()) return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); return date.toLocaleDateString([], { month: 'short', day: 'numeric' }) }
  function renderSessions() {
    const list = $('sessions'); const filtered = state.sessions.filter(s => titleFor(s).toLowerCase().includes(state.filter.toLowerCase()))
    $('sessionCount').textContent = filtered.length
    list.replaceChildren()
    if (!filtered.length) { const empty = document.createElement('div'); empty.className = 'session-meta'; empty.style.padding = '20px 10px'; empty.textContent = '没有匹配的会话'; list.appendChild(empty); return }
    filtered.forEach(item => { const row = document.createElement('button'); row.className = 'session' + (state.current === item.sessionId ? ' active' : ''); row.dataset.id = item.sessionId
      const mark = document.createElement('span'); mark.className = 'session-mark'; mark.textContent = '✦'; const copy = document.createElement('span'); copy.className = 'session-copy'; const title = document.createElement('span'); title.className = 'session-title'; title.textContent = titleFor(item); const meta = document.createElement('span'); meta.className = 'session-meta'; meta.textContent = item.cwd ? item.cwd.split(/[\\/]/).pop() + ' · ' + timeFor(item.updatedAt) : timeFor(item.updatedAt); copy.append(title, meta); const stateDot = document.createElement('span'); stateDot.className = 'session-state' + (item.running ? ' live' : ''); row.append(mark, copy, stateDot); row.addEventListener('click', () => openSession(item.sessionId)); list.appendChild(row) })
  }
  function addMessage(role, content, pending) { const wrap = document.createElement('div'); wrap.className = 'message ' + role + (pending ? ' pending' : ''); const avatar = document.createElement('div'); avatar.className = 'avatar'; avatar.textContent = role === 'user' ? '你' : 'D'; const body = document.createElement('div'); const bubble = document.createElement('div'); bubble.className = 'bubble'; bubble.textContent = content; body.appendChild(bubble); if (!pending) { const meta = document.createElement('div'); meta.className = 'message-meta'; meta.textContent = role === 'user' ? '刚刚' : (state.models?.current?.model || 'DSH'); body.appendChild(meta) } wrap.append(avatar, body); $('messages').appendChild(wrap); $('messages').scrollTop = $('messages').scrollHeight; return bubble }
  function renderHistory() { const container = $('messages'); container.replaceChildren(); const visible = state.history.filter(entry => ['user/message', 'assistant/message'].includes(entry.event?.type)); if (!visible.length) { const empty = document.createElement('div'); empty.className = 'empty'; empty.innerHTML = '<div class="empty-orb">✦</div><h2>你好，我是 DSH</h2><p>选择一个模型，开始你的下一次探索。</p><div class="quick-prompts"><button data-prompt="帮我分析这个项目的结构">分析项目结构</button><button data-prompt="写一个简洁的实现方案">设计实现方案</button><button data-prompt="解释这段代码的作用">解释代码</button></div>'; container.appendChild(empty); bindQuickPrompts(); return }
    visible.forEach(entry => { const role = entry.event.type.startsWith('user/') ? 'user' : 'assistant'; const content = messageText(entry.event.data); if (content.trim()) addMessage(role, content, false) })
  }
  async function openSession(id) { if (state.busy) return; state.current = id; const current = state.sessions.find(s => s.sessionId === id); $('sessionTitle').textContent = current ? titleFor(current) : '当前会话'; renderSessions(); try { const result = await rpc('session.history', { sessionId: id, maxMessages: 200 }); state.history = result.events || []; renderHistory(); const models = await rpc('session.models', { sessionId: id }); state.models = models; renderModel(); } catch (error) { setConnection(false); $('currentModel').textContent = '连接失败'; $('composerModelLabel').textContent = '连接失败'; toast(error.message) } }
  async function refreshSessions() { try { const result = await rpc('session.list', {}); state.sessions = result.items || []; renderSessions(); if (!state.current && state.sessions.length) await openSession(state.sessions[0].sessionId); else if (state.current && state.sessions.some(s => s.sessionId === state.current)) await openSession(state.current); } catch (error) { setConnection(false); toast('无法连接 DSH：' + error.message) } }
  async function newSession() { try { const result = await rpc('session.create', { cwd: (typeof process !== 'undefined' && process.env && process.env.USERPROFILE) ? process.env.USERPROFILE : '.' }); state.current = result.sessionId; await refreshSessions(); toast('已创建新会话') } catch (error) { toast(error.message) } }
  function displayGroups() { const live = state.models?.groups || []; const configured = state.modelConfig?.groups || []; if (!configured.length) return live; const used = new Set(); const ordered = configured.map(group => { const available = live.find(item => item.id === group.id); if (!available) return null; used.add(group.id); const models = group.models.map(model => available.models.find(item => item.id === model.id) || model).filter(model => model.id); return { ...available, name: group.name || available.name, models } }).filter(group => group && group.models.length); return ordered.concat(live.filter(group => !used.has(group.id))) }
  function renderModel() { const current = state.models?.current; const group = current && displayGroups().find(item => item.id === current.provider); const model = group && group.models.find(item => item.id === current.model); const modelName = model?.name || current?.model || '未选择'; const providerName = group?.name || current?.provider || ''; $('currentModel').textContent = current ? (providerName + ' / ' + modelName) : '未选择'; $('composerModelLabel').textContent = modelName; renderModelGroups() }
  function renderModelGroups() { const groups = displayGroups(); const target = $('modelGroups'); target.replaceChildren(); groups.forEach(group => { const card = document.createElement('div'); card.className = 'model-group'; const head = document.createElement('div'); head.className = 'model-group-head'; const name = document.createElement('strong'); name.textContent = group.name; const count = document.createElement('small'); count.textContent = group.models.length + ' 个模型'; head.append(name, count); const tags = document.createElement('div'); tags.className = 'model-tags'; group.models.forEach(model => { const tag = document.createElement('span'); tag.className = 'model-tag'; tag.textContent = model.name; tags.appendChild(tag) }); card.append(head, tags); target.appendChild(card) }) }
  function showModelMenu(anchor = $('composerModelPicker')) { const menu = $('modelMenu'); if (!state.models?.current || !anchor) { toast('模型列表还未加载完成'); return } menu.replaceChildren(); displayGroups().forEach(group => { const title = document.createElement('div'); title.className = 'group-title'; title.textContent = group.name; menu.appendChild(title); group.models.forEach(model => { const button = document.createElement('button'); button.className = 'model-option' + (state.models.current.model === model.id ? ' selected' : ''); const copy = document.createElement('span'); const strong = document.createElement('strong'); strong.textContent = model.name; const small = document.createElement('small'); small.textContent = group.name; copy.append(strong, small); const check = document.createElement('span'); check.className = 'check'; check.textContent = state.models.current.model === model.id ? '✓' : ''; button.append(copy, check); button.addEventListener('click', () => chooseModel(group.id, model.id)); menu.appendChild(button) }) }); menu.classList.remove('hidden'); const rect = anchor.getBoundingClientRect(); const opensUpward = anchor.id === 'composerModelPicker'; const top = opensUpward ? Math.max(8, rect.top - menu.offsetHeight - 8) : Math.min(window.innerHeight - menu.offsetHeight - 8, rect.bottom + 8); menu.style.top = top + 'px'; menu.style.left = Math.max(8, Math.min(window.innerWidth - menu.offsetWidth - 8, rect.left)) + 'px' }
  async function chooseModel(provider, model) { try { await rpc('session.selectModel', { sessionId: state.current, provider, model }); state.models.current = { provider, model }; renderModel(); $('modelMenu').classList.add('hidden'); toast('已切换到 ' + model) } catch (error) { toast(error.message) } }
  async function sendPrompt(value) { const content = value.trim(); if (!content || !state.current || state.busy) return; state.busy = true; $('statusText').textContent = '生成中…'; const empty = $('messages .empty'); if (empty) empty.remove(); addMessage('user', content, false); const bubble = addMessage('assistant', '正在思考…', true); try { await rpc('session.prompt', { sessionId: state.current, mode: 'queue', content: [{ type: 'text', text: content }], clientTimeZone: Intl.DateTimeFormat().resolvedOptions().timeZone }); bubble.textContent = '等待模型响应…'; } catch (error) { bubble.textContent = error.message; bubble.parentElement.parentElement.classList.add('error'); state.busy = false; $('statusText').textContent = '就绪' } }
  async function consumeEvents() { const poll = async () => { try { if (state.current) { const result = await rpc('session.history', { sessionId: state.current, maxMessages: 200 }); const next = result.events || []; if (next.length !== state.history.length) { state.history = next; renderHistory(); const last = next[next.length - 1]?.event?.type; if (last === 'assistant/message') { state.busy = false; $('statusText').textContent = '就绪' } } } } catch (_) { setConnection(false) } finally { setTimeout(poll, 1400) } }; poll() }
  function handleEvent(event) { if (event.type === 'assistant/message') { const content = messageText(event.data); const pending = [...$('messages').querySelectorAll('.message.pending')].pop(); if (pending) { pending.classList.remove('pending'); pending.querySelector('.bubble').textContent = content } else addMessage('assistant', content, false); state.busy = false; $('statusText').textContent = '就绪'; refreshSessions() } else if (event.type === 'assistant/chunk' && event.data?.chunk?.type === 'text_delta') { const pending = [...$('messages').querySelectorAll('.message.pending')].pop(); if (pending) pending.querySelector('.bubble').textContent = (pending.querySelector('.bubble').textContent === '正在思考…' || pending.querySelector('.bubble').textContent === '等待模型响应…' ? '' : pending.querySelector('.bubble').textContent) + (event.data.chunk.delta || '') } }
  function bindQuickPrompts() { document.querySelectorAll('[data-prompt]').forEach(button => button.addEventListener('click', () => { $('prompt').value = button.dataset.prompt; $('prompt').focus() })) }
  $('newSession').addEventListener('click', newSession); $('clearSession').addEventListener('click', newSession); $('refresh').addEventListener('click', refreshSessions); $('search').addEventListener('input', event => { state.filter = event.target.value; renderSessions() }); $('modelPicker').addEventListener('click', event => { event.stopPropagation(); showModelMenu(event.currentTarget) }); $('composerModelPicker').addEventListener('click', event => { event.preventDefault(); event.stopPropagation(); showModelMenu(event.currentTarget) }); document.addEventListener('click', event => { if (!event.target.closest('#modelMenu') && !event.target.closest('#modelPicker') && !event.target.closest('#composerModelPicker')) $('modelMenu').classList.add('hidden') }); $('settings').addEventListener('click', () => $('settingsPanel').classList.remove('hidden')); $('closeSettings').addEventListener('click', () => $('settingsPanel').classList.add('hidden')); $('copyAll').addEventListener('click', () => navigator.clipboard?.writeText([...document.querySelectorAll('.bubble')].map(node => node.textContent).join('\n\n')).then(() => toast('已复制全部消息'))); $('composer').addEventListener('submit', event => { event.preventDefault(); const input = $('prompt'); sendPrompt(input.value); input.value = ''; input.style.height = 'auto' }); $('prompt').addEventListener('keydown', event => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); $('composer').requestSubmit() } }); $('prompt').addEventListener('input', event => { event.target.style.height = 'auto'; event.target.style.height = Math.min(event.target.scrollHeight, 140) + 'px' }); bindQuickPrompts(); $('minimize').addEventListener('click', () => nativeInvoke('window_control', { action: 'minimize' })); $('maximize').addEventListener('click', () => nativeInvoke('window_control', { action: 'maximize' })); $('close').addEventListener('click', () => nativeInvoke('window_control', { action: 'close' }));
  async function loadModelConfig() { try { state.modelConfig = await nativeInvoke('model_groups', {}) } catch (_) { state.modelConfig = null } }
  (async function boot () { await loadModelConfig(); await refreshSessions(); consumeEvents() })()
})()
